name: CI

on: [pull_request]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --no-tags --prune --depth=5 origin main
      - uses: pnpm/action-setup@v2
        with:
          version: 8.7.4
      - uses: actions/setup-node@v3
        with:
          node-version: 18.17.1
          cache: 'pnpm'
      - run: pnpm install --ignore-scripts --frozen-lockfile
      - run: pnpm tsc
      - run: pnpm lint
      - run: pnpm test
      - run: pnpm build
